# Generated by Django 3.0.8 on 2025-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0005_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.RenameField(
            model_name='billdetails',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medical_typ',
            new_name='medical_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='c_gst',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='s_gst',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
