# Generated by Django 3.2.25 on 2025-02-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0006_auto_20250202_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='billdetails',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
