# Generated by Django 3.2.25 on 2025-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0015_auto_20250219_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='html_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
